import = [
  "~/.config/alacritty/themes/rose-pine.toml",
  "~/.config/alacritty/themes/rose-pine-moon.toml",
]

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14

[font.normal]
family = "Hasklug Nerd Font"
style = "normal"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
startup_mode = "Maximized"
